######################################################################
# Automatically generated by qmake (2.01a) mar mar 16 14:24:02 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += core \
	xml \
	gui \
	opengl
# Input
HEADERS += BezierGlyphBuilder.h GlyphPainter.h GlyphView.h
FORMS += BezierGlyphBuilder.ui
SOURCES += BezierGlyphBuilder.cpp GlyphPainter.cpp GlyphView.cpp main.cpp
